# Generated by Django 3.2.9 on 2021-12-01 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='catatalog_number',
            new_name='catalog_number',
        ),
    ]
