# Generated by Django 3.2.9 on 2021-12-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20211201_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
